<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>StardustInstaller</RootNamespace>
    <AssemblyName>StardustInstaller</AssemblyName>
    <Version>1.0.0</Version>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
</Project>
